### ISSUE TITLE
Warn users about unsaved annotations

### ISSUE THREAD

**Issue by ginic** [UMassCDS/inatator#93]
As an annotator
I want the UI to display a warning when I try to leave the webpage or close the window without saving annotations
so that no annotations are lost. 

Currently, it's very easy to exit the app without saving annotations and users may not realize that their work isn't saved to the database.

### Timebox [optional]
What's the maximum amount of time that should be spent working on this? 

### Definition of Done 
A checklist of things that need to happen in order for this story to be successfully completed
- [ ] Implement and check-in code changes
- [ ] Test code changes
- [ ] Documentation updated (if needed)
- [ ] Code review 

### Subtasks
You can add additional sub-tasks if you'd like to break down the work further.
